
namespace Loader
{
	partial class UserControl1
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserControl1));
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.codeModsTab1 = new Loader.CodeModsTab();
			this.SuspendLayout();
			// 
			// bunifuButton3
			// 
			this.bunifuButton3.AllowAnimations = true;
			this.bunifuButton3.AllowMouseEffects = true;
			this.bunifuButton3.AllowToggling = false;
			this.bunifuButton3.AnimationSpeed = 200;
			this.bunifuButton3.AutoGenerateColors = false;
			this.bunifuButton3.AutoRoundBorders = false;
			this.bunifuButton3.AutoSizeLeftIcon = true;
			this.bunifuButton3.AutoSizeRightIcon = true;
			this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
			this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.ButtonText = "Code Mods";
			this.bunifuButton3.ButtonTextMarginLeft = 0;
			this.bunifuButton3.ColorContrastOnClick = 45;
			this.bunifuButton3.ColorContrastOnHover = 45;
			this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges1.BottomLeft = true;
			borderEdges1.BottomRight = true;
			borderEdges1.TopLeft = true;
			borderEdges1.TopRight = true;
			this.bunifuButton3.CustomizableEdges = borderEdges1;
			this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton3.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton3.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton3.IconMarginLeft = 11;
			this.bunifuButton3.IconPadding = 10;
			this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton3.IconSize = 25;
			this.bunifuButton3.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton3.IdleBorderRadius = 20;
			this.bunifuButton3.IdleBorderThickness = 3;
			this.bunifuButton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton3.IdleIconLeftImage = null;
			this.bunifuButton3.IdleIconRightImage = null;
			this.bunifuButton3.IndicateFocus = true;
			this.bunifuButton3.Location = new System.Drawing.Point(26, 30);
			this.bunifuButton3.Name = "bunifuButton3";
			this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton3.OnDisabledState.BorderRadius = 20;
			this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.OnDisabledState.BorderThickness = 3;
			this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton3.OnDisabledState.IconLeftImage = null;
			this.bunifuButton3.OnDisabledState.IconRightImage = null;
			this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton3.onHoverState.BorderRadius = 20;
			this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.onHoverState.BorderThickness = 3;
			this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.onHoverState.IconLeftImage = null;
			this.bunifuButton3.onHoverState.IconRightImage = null;
			this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton3.OnIdleState.BorderRadius = 20;
			this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.OnIdleState.BorderThickness = 3;
			this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.OnIdleState.IconLeftImage = null;
			this.bunifuButton3.OnIdleState.IconRightImage = null;
			this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton3.OnPressedState.BorderRadius = 20;
			this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.OnPressedState.BorderThickness = 3;
			this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.OnPressedState.IconLeftImage = null;
			this.bunifuButton3.OnPressedState.IconRightImage = null;
			this.bunifuButton3.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton3.TabIndex = 18;
			this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton3.TextMarginLeft = 0;
			this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton3.UseDefaultRadiusAndThickness = true;
			this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
			// 
			// bunifuButton6
			// 
			this.bunifuButton6.AllowAnimations = true;
			this.bunifuButton6.AllowMouseEffects = true;
			this.bunifuButton6.AllowToggling = false;
			this.bunifuButton6.AnimationSpeed = 200;
			this.bunifuButton6.AutoGenerateColors = false;
			this.bunifuButton6.AutoRoundBorders = false;
			this.bunifuButton6.AutoSizeLeftIcon = true;
			this.bunifuButton6.AutoSizeRightIcon = true;
			this.bunifuButton6.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton6.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton6.BackgroundImage")));
			this.bunifuButton6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.ButtonText = "Support";
			this.bunifuButton6.ButtonTextMarginLeft = 0;
			this.bunifuButton6.ColorContrastOnClick = 45;
			this.bunifuButton6.ColorContrastOnHover = 45;
			this.bunifuButton6.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			this.bunifuButton6.CustomizableEdges = borderEdges2;
			this.bunifuButton6.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton6.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton6.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton6.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton6.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton6.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold);
			this.bunifuButton6.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton6.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton6.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton6.IconMarginLeft = 11;
			this.bunifuButton6.IconPadding = 10;
			this.bunifuButton6.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton6.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton6.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton6.IconSize = 25;
			this.bunifuButton6.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton6.IdleBorderRadius = 20;
			this.bunifuButton6.IdleBorderThickness = 3;
			this.bunifuButton6.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton6.IdleIconLeftImage = null;
			this.bunifuButton6.IdleIconRightImage = null;
			this.bunifuButton6.IndicateFocus = true;
			this.bunifuButton6.Location = new System.Drawing.Point(26, 165);
			this.bunifuButton6.Name = "bunifuButton6";
			this.bunifuButton6.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton6.OnDisabledState.BorderRadius = 20;
			this.bunifuButton6.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.OnDisabledState.BorderThickness = 3;
			this.bunifuButton6.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton6.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton6.OnDisabledState.IconLeftImage = null;
			this.bunifuButton6.OnDisabledState.IconRightImage = null;
			this.bunifuButton6.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton6.onHoverState.BorderRadius = 20;
			this.bunifuButton6.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.onHoverState.BorderThickness = 3;
			this.bunifuButton6.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton6.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.onHoverState.IconLeftImage = null;
			this.bunifuButton6.onHoverState.IconRightImage = null;
			this.bunifuButton6.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton6.OnIdleState.BorderRadius = 20;
			this.bunifuButton6.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.OnIdleState.BorderThickness = 3;
			this.bunifuButton6.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton6.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.OnIdleState.IconLeftImage = null;
			this.bunifuButton6.OnIdleState.IconRightImage = null;
			this.bunifuButton6.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton6.OnPressedState.BorderRadius = 20;
			this.bunifuButton6.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.OnPressedState.BorderThickness = 3;
			this.bunifuButton6.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton6.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.OnPressedState.IconLeftImage = null;
			this.bunifuButton6.OnPressedState.IconRightImage = null;
			this.bunifuButton6.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton6.TabIndex = 17;
			this.bunifuButton6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton6.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton6.TextMarginLeft = 0;
			this.bunifuButton6.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton6.UseDefaultRadiusAndThickness = true;
			// 
			// bunifuButton5
			// 
			this.bunifuButton5.AllowAnimations = true;
			this.bunifuButton5.AllowMouseEffects = true;
			this.bunifuButton5.AllowToggling = false;
			this.bunifuButton5.AnimationSpeed = 200;
			this.bunifuButton5.AutoGenerateColors = false;
			this.bunifuButton5.AutoRoundBorders = false;
			this.bunifuButton5.AutoSizeLeftIcon = true;
			this.bunifuButton5.AutoSizeRightIcon = true;
			this.bunifuButton5.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton5.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton5.BackgroundImage")));
			this.bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.ButtonText = "Settings";
			this.bunifuButton5.ButtonTextMarginLeft = 0;
			this.bunifuButton5.ColorContrastOnClick = 45;
			this.bunifuButton5.ColorContrastOnHover = 45;
			this.bunifuButton5.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			this.bunifuButton5.CustomizableEdges = borderEdges3;
			this.bunifuButton5.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton5.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton5.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton5.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton5.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton5.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton5.IconMarginLeft = 11;
			this.bunifuButton5.IconPadding = 10;
			this.bunifuButton5.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton5.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton5.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton5.IconSize = 25;
			this.bunifuButton5.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton5.IdleBorderRadius = 20;
			this.bunifuButton5.IdleBorderThickness = 3;
			this.bunifuButton5.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton5.IdleIconLeftImage = null;
			this.bunifuButton5.IdleIconRightImage = null;
			this.bunifuButton5.IndicateFocus = true;
			this.bunifuButton5.Location = new System.Drawing.Point(26, 120);
			this.bunifuButton5.Name = "bunifuButton5";
			this.bunifuButton5.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton5.OnDisabledState.BorderRadius = 20;
			this.bunifuButton5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.OnDisabledState.BorderThickness = 3;
			this.bunifuButton5.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton5.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton5.OnDisabledState.IconLeftImage = null;
			this.bunifuButton5.OnDisabledState.IconRightImage = null;
			this.bunifuButton5.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton5.onHoverState.BorderRadius = 20;
			this.bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.onHoverState.BorderThickness = 3;
			this.bunifuButton5.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton5.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.onHoverState.IconLeftImage = null;
			this.bunifuButton5.onHoverState.IconRightImage = null;
			this.bunifuButton5.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton5.OnIdleState.BorderRadius = 20;
			this.bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.OnIdleState.BorderThickness = 3;
			this.bunifuButton5.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton5.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.OnIdleState.IconLeftImage = null;
			this.bunifuButton5.OnIdleState.IconRightImage = null;
			this.bunifuButton5.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton5.OnPressedState.BorderRadius = 20;
			this.bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.OnPressedState.BorderThickness = 3;
			this.bunifuButton5.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton5.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.OnPressedState.IconLeftImage = null;
			this.bunifuButton5.OnPressedState.IconRightImage = null;
			this.bunifuButton5.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton5.TabIndex = 16;
			this.bunifuButton5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton5.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton5.TextMarginLeft = 0;
			this.bunifuButton5.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton5.UseDefaultRadiusAndThickness = true;
			// 
			// bunifuButton4
			// 
			this.bunifuButton4.AllowAnimations = true;
			this.bunifuButton4.AllowMouseEffects = true;
			this.bunifuButton4.AllowToggling = false;
			this.bunifuButton4.AnimationSpeed = 200;
			this.bunifuButton4.AutoGenerateColors = false;
			this.bunifuButton4.AutoRoundBorders = false;
			this.bunifuButton4.AutoSizeLeftIcon = true;
			this.bunifuButton4.AutoSizeRightIcon = true;
			this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
			this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.ButtonText = "Performance";
			this.bunifuButton4.ButtonTextMarginLeft = 0;
			this.bunifuButton4.ColorContrastOnClick = 45;
			this.bunifuButton4.ColorContrastOnHover = 45;
			this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			this.bunifuButton4.CustomizableEdges = borderEdges4;
			this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton4.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton4.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton4.IconMarginLeft = 11;
			this.bunifuButton4.IconPadding = 10;
			this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton4.IconSize = 25;
			this.bunifuButton4.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton4.IdleBorderRadius = 20;
			this.bunifuButton4.IdleBorderThickness = 3;
			this.bunifuButton4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton4.IdleIconLeftImage = null;
			this.bunifuButton4.IdleIconRightImage = null;
			this.bunifuButton4.IndicateFocus = true;
			this.bunifuButton4.Location = new System.Drawing.Point(26, 75);
			this.bunifuButton4.Name = "bunifuButton4";
			this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton4.OnDisabledState.BorderRadius = 20;
			this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.OnDisabledState.BorderThickness = 3;
			this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton4.OnDisabledState.IconLeftImage = null;
			this.bunifuButton4.OnDisabledState.IconRightImage = null;
			this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton4.onHoverState.BorderRadius = 20;
			this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.onHoverState.BorderThickness = 3;
			this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.onHoverState.IconLeftImage = null;
			this.bunifuButton4.onHoverState.IconRightImage = null;
			this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton4.OnIdleState.BorderRadius = 20;
			this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.OnIdleState.BorderThickness = 3;
			this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.OnIdleState.IconLeftImage = null;
			this.bunifuButton4.OnIdleState.IconRightImage = null;
			this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton4.OnPressedState.BorderRadius = 20;
			this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.OnPressedState.BorderThickness = 3;
			this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.OnPressedState.IconLeftImage = null;
			this.bunifuButton4.OnPressedState.IconRightImage = null;
			this.bunifuButton4.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton4.TabIndex = 15;
			this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton4.TextMarginLeft = 0;
			this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton4.UseDefaultRadiusAndThickness = true;
			// 
			// bunifuButton1
			// 
			this.bunifuButton1.AllowAnimations = true;
			this.bunifuButton1.AllowMouseEffects = true;
			this.bunifuButton1.AllowToggling = false;
			this.bunifuButton1.AnimationSpeed = 200;
			this.bunifuButton1.AutoGenerateColors = false;
			this.bunifuButton1.AutoRoundBorders = false;
			this.bunifuButton1.AutoSizeLeftIcon = true;
			this.bunifuButton1.AutoSizeRightIcon = true;
			this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
			this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.ButtonText = "Mods";
			this.bunifuButton1.ButtonTextMarginLeft = 0;
			this.bunifuButton1.ColorContrastOnClick = 45;
			this.bunifuButton1.ColorContrastOnHover = 45;
			this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			this.bunifuButton1.CustomizableEdges = borderEdges5;
			this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton1.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton1.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton1.IconMarginLeft = 11;
			this.bunifuButton1.IconPadding = 10;
			this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton1.IconSize = 25;
			this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton1.IdleBorderRadius = 20;
			this.bunifuButton1.IdleBorderThickness = 3;
			this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton1.IdleIconLeftImage = null;
			this.bunifuButton1.IdleIconRightImage = null;
			this.bunifuButton1.IndicateFocus = true;
			this.bunifuButton1.Location = new System.Drawing.Point(26, 210);
			this.bunifuButton1.Name = "bunifuButton1";
			this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton1.OnDisabledState.BorderRadius = 20;
			this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnDisabledState.BorderThickness = 3;
			this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton1.OnDisabledState.IconLeftImage = null;
			this.bunifuButton1.OnDisabledState.IconRightImage = null;
			this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton1.onHoverState.BorderRadius = 20;
			this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.onHoverState.BorderThickness = 3;
			this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.onHoverState.IconLeftImage = null;
			this.bunifuButton1.onHoverState.IconRightImage = null;
			this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton1.OnIdleState.BorderRadius = 20;
			this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnIdleState.BorderThickness = 3;
			this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.OnIdleState.IconLeftImage = null;
			this.bunifuButton1.OnIdleState.IconRightImage = null;
			this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton1.OnPressedState.BorderRadius = 20;
			this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnPressedState.BorderThickness = 3;
			this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.OnPressedState.IconLeftImage = null;
			this.bunifuButton1.OnPressedState.IconRightImage = null;
			this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton1.TabIndex = 22;
			this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton1.TextMarginLeft = 0;
			this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton1.UseDefaultRadiusAndThickness = true;
			// 
			// bunifuButton2
			// 
			this.bunifuButton2.AllowAnimations = true;
			this.bunifuButton2.AllowMouseEffects = true;
			this.bunifuButton2.AllowToggling = false;
			this.bunifuButton2.AnimationSpeed = 200;
			this.bunifuButton2.AutoGenerateColors = false;
			this.bunifuButton2.AutoRoundBorders = false;
			this.bunifuButton2.AutoSizeLeftIcon = true;
			this.bunifuButton2.AutoSizeRightIcon = true;
			this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
			this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.ButtonText = "Support";
			this.bunifuButton2.ButtonTextMarginLeft = 0;
			this.bunifuButton2.ColorContrastOnClick = 45;
			this.bunifuButton2.ColorContrastOnHover = 45;
			this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges6.BottomLeft = true;
			borderEdges6.BottomRight = true;
			borderEdges6.TopLeft = true;
			borderEdges6.TopRight = true;
			this.bunifuButton2.CustomizableEdges = borderEdges6;
			this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton2.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold);
			this.bunifuButton2.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton2.IconMarginLeft = 11;
			this.bunifuButton2.IconPadding = 10;
			this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton2.IconSize = 25;
			this.bunifuButton2.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton2.IdleBorderRadius = 20;
			this.bunifuButton2.IdleBorderThickness = 3;
			this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton2.IdleIconLeftImage = null;
			this.bunifuButton2.IdleIconRightImage = null;
			this.bunifuButton2.IndicateFocus = true;
			this.bunifuButton2.Location = new System.Drawing.Point(26, 345);
			this.bunifuButton2.Name = "bunifuButton2";
			this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton2.OnDisabledState.BorderRadius = 20;
			this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnDisabledState.BorderThickness = 3;
			this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton2.OnDisabledState.IconLeftImage = null;
			this.bunifuButton2.OnDisabledState.IconRightImage = null;
			this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton2.onHoverState.BorderRadius = 20;
			this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.onHoverState.BorderThickness = 3;
			this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.onHoverState.IconLeftImage = null;
			this.bunifuButton2.onHoverState.IconRightImage = null;
			this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton2.OnIdleState.BorderRadius = 20;
			this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnIdleState.BorderThickness = 3;
			this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.OnIdleState.IconLeftImage = null;
			this.bunifuButton2.OnIdleState.IconRightImage = null;
			this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton2.OnPressedState.BorderRadius = 20;
			this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnPressedState.BorderThickness = 3;
			this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.OnPressedState.IconLeftImage = null;
			this.bunifuButton2.OnPressedState.IconRightImage = null;
			this.bunifuButton2.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton2.TabIndex = 21;
			this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton2.TextMarginLeft = 0;
			this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton2.UseDefaultRadiusAndThickness = true;
			// 
			// bunifuButton7
			// 
			this.bunifuButton7.AllowAnimations = true;
			this.bunifuButton7.AllowMouseEffects = true;
			this.bunifuButton7.AllowToggling = false;
			this.bunifuButton7.AnimationSpeed = 200;
			this.bunifuButton7.AutoGenerateColors = false;
			this.bunifuButton7.AutoRoundBorders = false;
			this.bunifuButton7.AutoSizeLeftIcon = true;
			this.bunifuButton7.AutoSizeRightIcon = true;
			this.bunifuButton7.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton7.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.BackgroundImage")));
			this.bunifuButton7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton7.ButtonText = "Settings";
			this.bunifuButton7.ButtonTextMarginLeft = 0;
			this.bunifuButton7.ColorContrastOnClick = 45;
			this.bunifuButton7.ColorContrastOnHover = 45;
			this.bunifuButton7.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges7.BottomLeft = true;
			borderEdges7.BottomRight = true;
			borderEdges7.TopLeft = true;
			borderEdges7.TopRight = true;
			this.bunifuButton7.CustomizableEdges = borderEdges7;
			this.bunifuButton7.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton7.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton7.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton7.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton7.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton7.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton7.ForeColor = System.Drawing.Color.White;
			this.bunifuButton7.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton7.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton7.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton7.IconMarginLeft = 11;
			this.bunifuButton7.IconPadding = 10;
			this.bunifuButton7.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton7.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton7.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton7.IconSize = 25;
			this.bunifuButton7.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton7.IdleBorderRadius = 20;
			this.bunifuButton7.IdleBorderThickness = 3;
			this.bunifuButton7.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton7.IdleIconLeftImage = null;
			this.bunifuButton7.IdleIconRightImage = null;
			this.bunifuButton7.IndicateFocus = true;
			this.bunifuButton7.Location = new System.Drawing.Point(26, 300);
			this.bunifuButton7.Name = "bunifuButton7";
			this.bunifuButton7.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton7.OnDisabledState.BorderRadius = 20;
			this.bunifuButton7.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton7.OnDisabledState.BorderThickness = 3;
			this.bunifuButton7.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton7.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton7.OnDisabledState.IconLeftImage = null;
			this.bunifuButton7.OnDisabledState.IconRightImage = null;
			this.bunifuButton7.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton7.onHoverState.BorderRadius = 20;
			this.bunifuButton7.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton7.onHoverState.BorderThickness = 3;
			this.bunifuButton7.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton7.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton7.onHoverState.IconLeftImage = null;
			this.bunifuButton7.onHoverState.IconRightImage = null;
			this.bunifuButton7.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton7.OnIdleState.BorderRadius = 20;
			this.bunifuButton7.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton7.OnIdleState.BorderThickness = 3;
			this.bunifuButton7.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton7.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton7.OnIdleState.IconLeftImage = null;
			this.bunifuButton7.OnIdleState.IconRightImage = null;
			this.bunifuButton7.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton7.OnPressedState.BorderRadius = 20;
			this.bunifuButton7.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton7.OnPressedState.BorderThickness = 3;
			this.bunifuButton7.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton7.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton7.OnPressedState.IconLeftImage = null;
			this.bunifuButton7.OnPressedState.IconRightImage = null;
			this.bunifuButton7.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton7.TabIndex = 20;
			this.bunifuButton7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton7.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton7.TextMarginLeft = 0;
			this.bunifuButton7.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton7.UseDefaultRadiusAndThickness = true;
			// 
			// bunifuButton8
			// 
			this.bunifuButton8.AllowAnimations = true;
			this.bunifuButton8.AllowMouseEffects = true;
			this.bunifuButton8.AllowToggling = false;
			this.bunifuButton8.AnimationSpeed = 200;
			this.bunifuButton8.AutoGenerateColors = false;
			this.bunifuButton8.AutoRoundBorders = false;
			this.bunifuButton8.AutoSizeLeftIcon = true;
			this.bunifuButton8.AutoSizeRightIcon = true;
			this.bunifuButton8.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton8.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton8.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton8.BackgroundImage")));
			this.bunifuButton8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton8.ButtonText = "Performance";
			this.bunifuButton8.ButtonTextMarginLeft = 0;
			this.bunifuButton8.ColorContrastOnClick = 45;
			this.bunifuButton8.ColorContrastOnHover = 45;
			this.bunifuButton8.Cursor = System.Windows.Forms.Cursors.Default;
			borderEdges8.BottomLeft = true;
			borderEdges8.BottomRight = true;
			borderEdges8.TopLeft = true;
			borderEdges8.TopRight = true;
			this.bunifuButton8.CustomizableEdges = borderEdges8;
			this.bunifuButton8.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton8.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton8.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton8.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton8.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton8.Font = new System.Drawing.Font("Dosis", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton8.ForeColor = System.Drawing.Color.White;
			this.bunifuButton8.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton8.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton8.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton8.IconMarginLeft = 11;
			this.bunifuButton8.IconPadding = 10;
			this.bunifuButton8.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton8.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton8.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton8.IconSize = 25;
			this.bunifuButton8.IdleBorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton8.IdleBorderRadius = 20;
			this.bunifuButton8.IdleBorderThickness = 3;
			this.bunifuButton8.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton8.IdleIconLeftImage = null;
			this.bunifuButton8.IdleIconRightImage = null;
			this.bunifuButton8.IndicateFocus = true;
			this.bunifuButton8.Location = new System.Drawing.Point(26, 255);
			this.bunifuButton8.Name = "bunifuButton8";
			this.bunifuButton8.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton8.OnDisabledState.BorderRadius = 20;
			this.bunifuButton8.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton8.OnDisabledState.BorderThickness = 3;
			this.bunifuButton8.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton8.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton8.OnDisabledState.IconLeftImage = null;
			this.bunifuButton8.OnDisabledState.IconRightImage = null;
			this.bunifuButton8.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton8.onHoverState.BorderRadius = 20;
			this.bunifuButton8.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton8.onHoverState.BorderThickness = 3;
			this.bunifuButton8.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton8.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton8.onHoverState.IconLeftImage = null;
			this.bunifuButton8.onHoverState.IconRightImage = null;
			this.bunifuButton8.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
			this.bunifuButton8.OnIdleState.BorderRadius = 20;
			this.bunifuButton8.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton8.OnIdleState.BorderThickness = 3;
			this.bunifuButton8.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
			this.bunifuButton8.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton8.OnIdleState.IconLeftImage = null;
			this.bunifuButton8.OnIdleState.IconRightImage = null;
			this.bunifuButton8.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(97)))), ((int)(((byte)(97)))));
			this.bunifuButton8.OnPressedState.BorderRadius = 20;
			this.bunifuButton8.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton8.OnPressedState.BorderThickness = 3;
			this.bunifuButton8.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(81)))), ((int)(((byte)(81)))));
			this.bunifuButton8.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton8.OnPressedState.IconLeftImage = null;
			this.bunifuButton8.OnPressedState.IconRightImage = null;
			this.bunifuButton8.Size = new System.Drawing.Size(150, 39);
			this.bunifuButton8.TabIndex = 19;
			this.bunifuButton8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton8.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton8.TextMarginLeft = 0;
			this.bunifuButton8.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton8.UseDefaultRadiusAndThickness = true;
			// 
			// codeModsTab1
			// 
			this.codeModsTab1.Location = new System.Drawing.Point(182, 3);
			this.codeModsTab1.Name = "codeModsTab1";
			this.codeModsTab1.Size = new System.Drawing.Size(611, 425);
			this.codeModsTab1.TabIndex = 23;
			// 
			// UserControl1
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this.codeModsTab1);
			this.Controls.Add(this.bunifuButton1);
			this.Controls.Add(this.bunifuButton2);
			this.Controls.Add(this.bunifuButton7);
			this.Controls.Add(this.bunifuButton8);
			this.Controls.Add(this.bunifuButton3);
			this.Controls.Add(this.bunifuButton6);
			this.Controls.Add(this.bunifuButton5);
			this.Controls.Add(this.bunifuButton4);
			this.Name = "UserControl1";
			this.Size = new System.Drawing.Size(793, 431);
			this.Load += new System.EventHandler(this.UserControl1_Load);
			this.ResumeLayout(false);

		}

		#endregion

		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton6;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton7;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton8;
		private CodeModsTab codeModsTab1;
	}
}
